version: '3.8'
services:
  app:
    build: 
      context: .
      dockerfile: dockerfile
    image: 'my-app:slim'
    ports:
        - "5000:5000"
    depends_on:
        - db
        - redis
    env_file:
      - ./env/app.env
    volumes:
        - ./app.py:/app/app.py
        - .:/app
  db:
    image: 'postgres:16'
    ports:
        - "5432:5432"
    env_file:
      - ./env/db.env
    volumes:
        - db-data:/var/lib/postgresql/data
  redis:
    image: 'redis'
    ports:
        - "6379:6379"
volumes:
  db-data:
