apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-flask-deployment
  namespace: devops-tools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask-container
        image: docker.io/b4w4rzr1ng/jenkins:latest
        ports:
        - containerPort: 5000
